### ISSUE TITLE
Welcome to shopify-template-ruby Discussions!

### ISSUE THREAD

**Issue by philipabak** [philipabak/shopify-template-ruby#4]
### Discussed in https://github.com/philipabak/shopify-template-ruby/discussions/3

<div type='discussions-op-text'>

<sup>Originally posted by **philipabak** May  3, 2024</sup>

## 👋 Welcome!
  We’re using Discussions as a place to connect with other members of our community. We hope that you:
  * Ask questions you’re wondering about.
  * Share ideas.
  * Engage with other community members.
  * Welcome others and are open-minded. Remember that this is a community we
  build together 💪.

  To get started, comment below with an introduction of yourself and tell us about what you do with this community.

</div>

**Comment by philipabak** [comment]
I'd like to discuss with all.

**Comment by wenyigamba** [comment]
Thanks.
